# Generated by Django 5.1.2 on 2024-11-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_alter_recipe_author_alter_recipe_categories_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
