# Generated by Django 5.1.2 on 2024-11-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_rename_user_comment_author_alter_comment_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
